name: ai_typing
description: "A package to simulate AI typing text."
version: 0.0.1
homepage: https://github.com/iktakahiro/flutter-ai-typing

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
